"""Initial migration

Revision ID: b9c46c5ef6bd
Revises: 
Create Date: 2022-10-20 17:39:28.713785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c46c5ef6bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('salary', sa.String(length=50), nullable=False),
    sa.Column('job_category', sa.String(length=20), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('salary', sa.VARCHAR(length=50), nullable=False),
    sa.Column('job_category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('advertisment')
    # ### end Alembic commands ###
